version: "3.8"
services:
  postgres:
    container_name: postgres_sb_img
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_auto
    ports:
      - "5432:5432"
    volumes:
      #      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
      - /postgres-data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq_sb_container
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # Main LocalStack port
      - "4577:4577"   # SQS
    environment:
      - SERVICES=,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1

#volumes:
#  postgres-data:
