spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true

  flyway:
    enabled: true

api:
  security:
    token:
      secret: BE1B44F8953BB2978C54FAA622EA1