spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_auto
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: false

  flyway:
    enabled: false

api:
  security:
    token:
      secret: BE1B44F8953BB2978C54FAA622EA1

aws:
  sqs:
    name: "sqs-rent-queue"