server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://db:5432/project_auto
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

  flyway:
    enabled: false