server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_auto?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: true

  flyway:
    enabled: false
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration